(defpackage #:luv.vk
  (:nicknames #:vk)
  (:use)
  (:documentation
   "The Vulkan entry points luv speaks, one external function per foreign
entry point.  DEFVKFUN interns and exports here; nothing else does."))

(defpackage #:luv.vulkan
  (:nicknames #:lvk)
  (:use #:cl)
  (:export #:+portability-enumeration-extension-name+
           #:+swapchain-extension-name+
           #:+debug-utils-extension-name+
           #:vulkan-call-error
           #:vulkan-call-error-operation
           #:vulkan-call-error-result
           #:vulkan-call-event
           #:vulkan-call-event-sequence
           #:vulkan-call-event-timestamp
           #:vulkan-call-event-duration
           #:vulkan-call-event-thread
           #:vulkan-call-event-name
           #:vulkan-call-event-foreign-name
           #:vulkan-call-event-arguments
           #:vulkan-call-event-values
           #:vulkan-call-event-status
           #:vulkan-call-event-condition
           #:vulkan-trace
           #:vulkan-trace-events
           #:start-vulkan-trace
           #:stop-vulkan-trace
           #:current-vulkan-trace
           #:with-vulkan-trace
           #:vulkan-trace-presentation-intervals
           #:vulkan-function-description
           #:make-version
           #:enumerate-instance-extension-names
           #:create-instance
           #:destroy-instance
           #:debug-message
           #:debug-message-severity
           #:debug-message-types
           #:debug-message-id-name
           #:debug-message-id-number
           #:debug-message-text
           #:debug-messenger
           #:debug-messenger-destroyed-p
           #:install-debug-messenger
           #:destroy-debug-messenger
           #:enumerate-physical-devices
           #:queue-family
           #:queue-family-flags
           #:queue-family-count
           #:physical-device-queue-families
           #:physical-memory-type
           #:physical-memory-type-flags
           #:physical-memory-type-heap-index
           #:physical-device-memory-types
           #:create-device
           #:destroy-device
           #:get-device-queue
           #:device-wait-idle
           #:create-image
           #:destroy-image
           #:image-memory-requirements
           #:image-memory-requirements-size
           #:image-memory-requirements-alignment
           #:image-memory-requirements-memory-type-bits
           #:get-image-memory-requirements
           #:create-buffer
           #:destroy-buffer
           #:buffer-memory-requirements
           #:buffer-memory-requirements-size
           #:buffer-memory-requirements-alignment
           #:buffer-memory-requirements-memory-type-bits
           #:get-buffer-memory-requirements
           #:allocate-memory
           #:free-memory
           #:bind-image-memory
           #:bind-buffer-memory
           #:map-memory
           #:unmap-memory
           #:create-image-view
           #:destroy-image-view
           #:create-shader-module
           #:destroy-shader-module
           #:create-storage-image-descriptor-set-layout
           #:create-uniform-buffer-descriptor-set-layout
           #:create-texture-sampler-uniform-descriptor-set-layout
           #:destroy-descriptor-set-layout
           #:create-pipeline-layout
           #:destroy-pipeline-layout
           #:create-compute-pipeline
           #:create-graphics-pipeline
           #:destroy-pipeline
           #:create-sampler
           #:destroy-sampler
           #:create-color-render-pass
           #:create-depth-render-pass
           #:destroy-render-pass
           #:create-framebuffer
           #:destroy-framebuffer
           #:create-storage-image-descriptor-pool
           #:create-uniform-buffer-descriptor-pool
           #:create-texture-sampler-uniform-descriptor-pool
           #:destroy-descriptor-pool
           #:allocate-descriptor-set
           #:update-storage-image-descriptor
           #:update-uniform-buffer-descriptor
           #:update-texture-sampler-uniform-descriptors
           #:create-command-pool
           #:destroy-command-pool
           #:allocate-command-buffer
           #:begin-command-buffer
           #:end-command-buffer
           #:cmd-transition-image
           #:cmd-clear-color-image
           #:cmd-copy-image
           #:cmd-copy-buffer-to-image
           #:cmd-copy-image-to-buffer
           #:cmd-bind-compute-pipeline
           #:cmd-bind-graphics-pipeline
           #:cmd-bind-compute-descriptor-set
           #:cmd-bind-graphics-descriptor-set
           #:cmd-bind-vertex-buffer
           #:cmd-dispatch
           #:cmd-begin-color-render-pass
           #:cmd-begin-depth-render-pass
           #:cmd-set-viewport-and-scissor
           #:cmd-end-render-pass
           #:cmd-draw
           #:submit-command-buffers
           #:submit-command-buffer
           #:queue-wait-idle
           #:surface-supported-p
           #:presentation-capabilities
           #:presentation-capabilities-min-image-count
           #:presentation-capabilities-max-image-count
           #:presentation-capabilities-current-extent
           #:presentation-capabilities-min-image-extent
           #:presentation-capabilities-max-image-extent
           #:presentation-capabilities-current-transform
           #:presentation-capabilities-composite-alpha
           #:presentation-capabilities-usage
           #:get-surface-capabilities
           #:presentation-format
           #:presentation-format-format
           #:presentation-format-color-space
           #:get-surface-formats
           #:get-surface-present-modes
           #:create-swapchain
           #:destroy-swapchain
           #:get-swapchain-images
           #:create-semaphore
           #:create-timeline-semaphore
           #:destroy-semaphore
           #:semaphore-counter-value
           #:wait-semaphore-value
           #:acquire-next-image
           #:present))

;;; LUV is the public GPU, canvas, and native-host vocabulary.  The block
;;; world and application live in LUVCRAFT.WORLD and LUVCRAFT.

(defpackage #:luv
  (:use #:cl)
  (:export #:*gpu-provider*
           #:*cpu-trace*
           #:cpu-trace
           #:cpu-trace-zone
           #:make-cpu-trace
           #:reset-cpu-trace
           #:with-cpu-trace
           #:with-cpu-trace-zone
           #:cpu-trace-zones
           #:cpu-trace-zone-name
           #:cpu-trace-zone-parent-index
           #:cpu-trace-zone-depth
           #:cpu-trace-zone-seconds
           #:print-cpu-trace
           #:gpu-error
           #:gpu-error-operation
           #:gpu-request-error
           #:gpu-request-error-descriptor
           #:gpu-request-error-reason
           #:gpu-request-error-details
           #:gpu-object-error
           #:gpu-object-error-object
           #:gpu-object-destroyed-error
           #:gpu-invalid-state-error
           #:gpu-invalid-state-error-state
           #:gpu-invalid-state-error-expected-state
           #:gpu-device-mismatch-error
           #:gpu-device-mismatch-error-expected-device
           #:gpu-device-mismatch-error-actual-device
           #:gpu-usage-error
           #:gpu-usage-error-required-usage
           #:gpu-usage-error-actual-usage
           #:gpu-resource-leaked
           #:gpu-resource-leaked-class
           #:gpu-resource-leaked-label
           #:*leaked-gpu-resources*
           #:vulkan-gpu-error
           #:vulkan-gpu-error-reason
           #:vulkan-gpu-error-details
           #:gpu-provider
           #:gpu-device
           #:gpu-queue
           #:gpu-buffer
           #:gpu-buffer-size
           #:gpu-buffer-usage
           #:gpu-texture
           #:gpu-texture-size
           #:gpu-texture-usage
           #:gpu-texture-dimensions
           #:gpu-texture-format
           #:gpu-texture-view
           #:gpu-texture-view-texture
           #:gpu-sampler
           #:gpu-shader-module
           #:gpu-bind-group-layout
           #:gpu-bind-group
           #:gpu-compute-pipeline
           #:gpu-render-pipeline
           #:gpu-encoder
           #:gpu-render-pass-encoder
           #:gpu-compute-pass-encoder
           #:gpu-command-encoder
           #:gpu-command-buffer
           #:gpu-command
           #:gpu-queue-command
           #:gpu-command-encoder-command
           #:gpu-pass-command
           #:gpu-render-pass-command
           #:gpu-compute-pass-command
           #:gpu-draw-command
           #:gpu-set-pipeline-command
           #:gpu-set-bind-group-command
           #:gpu-set-vertex-buffer-command
           #:gpu-dispatch-workgroups-command
           #:gpu-clear-texture-command
           #:gpu-copy-texture-command
           #:gpu-copy-texture-to-buffer-command
           #:gpu-write-texture-command
           #:gpu-prepare-texture-command
           #:gpu-object-label
           #:request-gpu-device
           #:device-queue
           #:create
           #:encode
           #:enqueue
           #:finish
           #:submit
           #:submitted-work-done
           #:write-buffer
           #:read-buffer
           #:write-texture
           #:destroy
           #:begin-compute-pass
           #:begin-render-pass
           #:end-pass
           #:set-pipeline
           #:set-bind-group
           #:set-vertex-buffer
           #:dispatch-workgroups
           #:draw
           #:make-device-descriptor
           #:make-buffer-descriptor
           #:make-texture-descriptor
           #:texture-format-bytes-per-texel
           #:texture-format-sample-transfer
           #:make-texture-copy
           #:texture-copy-texture
           #:texture-copy-mip-level
           #:texture-copy-origin
           #:texture-copy-aspect
           #:make-texture-data-layout
           #:texture-data-layout-offset
           #:texture-data-layout-bytes-per-row
           #:texture-data-layout-rows-per-image
           #:make-texture-view-descriptor
           #:make-sampler-descriptor
           #:make-shader-module-descriptor
           #:shader-module-descriptor-code
           #:shader-module-descriptor-language
           #:make-bind-group-layout-descriptor
           #:make-bind-group-descriptor
           #:make-compute-pipeline-descriptor
           #:make-render-pipeline-descriptor
           #:make-render-pass-descriptor
           #:make-command-encoder-descriptor
           #:make-gpu-clear-texture-command
           #:make-gpu-copy-texture-command
           #:make-gpu-copy-texture-to-buffer-command
           #:make-gpu-write-texture-command
           #:make-gpu-prepare-texture-command
           #:prepare-texture
           #:make-gpu-set-pipeline-command
           #:make-gpu-set-bind-group-command
           #:make-gpu-set-vertex-buffer-command
           #:make-gpu-dispatch-workgroups-command
           #:make-gpu-draw-command
           #:vulkan-gpu-provider
           #+darwin
           #:metal-gpu-provider
           #+darwin
           #:metal-gpu-device
           #+darwin
           #:metal-gpu-queue
           #+darwin
           #:metal-gpu-command-encoder
           #+darwin
           #:metal-gpu-command-buffer
           #+darwin
           #:metal-gpu-buffer
           #+darwin
           #:metal-gpu-texture
           #+darwin
           #:metal-gpu-shader-module
           #+darwin
           #:metal-gpu-render-pipeline
           #+darwin
           #:metal-device-compiler
           #+darwin
           #:metal-shader-module-document
           #+darwin
           #:metal-shader-module-entry-point
           #+darwin
           #:metal-shader-module-function-type
           #+darwin
           #:metal-render-pipeline-depth-stencil-state
           #+darwin
           #:metal-render-pipeline-vertex-buffers
           #+darwin
           #:metal-render-pass-encoder
           #+darwin
           #:metal-render-pass-argument-table
           #:vulkan-provider-application-name
           #:vulkan-provider-debug-callback
           #:vulkan-provider-debug-severities
           #:vulkan-provider-debug-types
           #:vulkan-device-instance-extension-names
           #:vulkan-device-debug-messenger
           #:canvas-clock
           #:canvas-event-handler
           #:canvas-event
           #:canvas-event-timestamp
           #:canvas-pointer-event
           #:canvas-pointer-event-x
           #:canvas-pointer-event-y
           #:canvas-pointer-event-delta-x
           #:canvas-pointer-event-delta-y
           #:canvas-pointer-motion-event
           #:canvas-pointer-enter-event
           #:canvas-pointer-exit-event
           #:canvas-pointer-button-event
           #:canvas-pointer-event-button
           #:canvas-pointer-event-clicks
           #:canvas-pointer-button-press-event
           #:canvas-pointer-button-release-event
           #:canvas-key-event
           #:canvas-key-event-key-name
           #:canvas-key-event-modifiers
           #:canvas-key-event-character
           #:canvas-key-event-repeat-p
           #:canvas-key-press-event
           #:canvas-key-release-event
           #:canvas-window-event
           #:canvas-window-size-event
           #:canvas-window-event-width
           #:canvas-window-event-height
           #:canvas-window-resized-event
           #:canvas-window-pixel-size-changed-event
           #:canvas-window-focus-gained-event
           #:canvas-window-focus-lost-event
           #:canvas-window-close-request-event
           #:handle-canvas-event
           #:demand-clock
           #:cadence-clock
           #:make-demand-clock
           #:make-cadence-clock
           #:clock-frames-per-second
           #:clock-frame-function
           #:clock-wait-timeout
           #:service-canvas-clock
           #:canvas
           #:canvas-context
           #:context-canvas
           #:context-device
           #:canvas-error
           #:canvas-error-canvas
           #:canvas-error-operation
           #:canvas-error-reason
           #:canvas-error-details
           #:canvas-state-error
           #:canvas-state-error-state
           #:canvas-state-error-expected-state
           #:canvas-configuration
           #:make-canvas-configuration
           #:canvas-configuration-device
           #:canvas-configuration-format
           #:canvas-configuration-usage
           #:get-current-texture
           #:sdl-canvas
           #:make-sdl-canvas
           #:sdl-canvas-presentation-api
           #:vulkan-canvas-context
           #+darwin
           #:metal-canvas-context
           #:canvas-title
           #:canvas-width
           #:canvas-height
           #:canvas-size
           #:canvas-logical-size
           #:canvas-position
           #:canvas-visible-p
           #:set-canvas-relative-pointer-mode
           #:show-canvas
           #:hide-canvas
           #:move-canvas
           #:resize-canvas
           #:raise-canvas
           #:minimize-canvas
           #:restore-canvas
           #:request-canvas-frame
           #:make-canvas-context
           #:configure-canvas-context
           #:unconfigure-canvas-context
           #:destroy-canvas-context
           #:call-with-canvas-frame
           #:canvas-device
           #:canvas-extent
           #:canvas-format
           #:canvas-state
           #:canvas-context-state
           #:canvas-frame-resource-key
           #:call-with-sdl-main-thread
           #:open-canvas
           #:present-canvas-frame
           #:render-canvas-color
           #+darwin
           #:probe-sdl-metal-clear
           #+darwin
           #:probe-metal-shader-library
           #:probe-metal-render-pipeline
           #:clear-color-demo
           #:demo-canvas
           #:demo-context
           #:demo-speed
           #:start-clear-color-demo
           #:stop-clear-color-demo
           #:compute-gradient-demo
           #:start-compute-gradient-demo
           #:stop-compute-gradient-demo
           #:render-metal-slug-bezier-proof
           #:render-metal-slug-outline
           #:render-metal-slug-glyph
           #:write-rgba-png
           #:close-canvas))
