(defpackage #:luv.tracy.capture
  (:use #:cl)
  (:export #:*tracy-capture-program-environment*
           #:*tracy-profiler-program-environment*
           #:tracy-capture-runtime
           #:native-tracy-capture-runtime
           #:tracy-clock-now
           #:tracy-path-exists-p
           #:prepare-tracy-client
           #:tracy-viewer-connected-p
           #:resolve-tracy-program
           #:launch-tracy-process
           #:tracy-process-alive-p
           #:interrupt-tracy-process
           #:terminate-tracy-process
           #:wait-tracy-process
           #:tracy-process-exit-code
           #:close-tracy-process
           #:tracy-capture-diagnostic
           #:tracy-capture-diagnostic-operation
           #:tracy-capture-diagnostic-state
           #:tracy-capture-diagnostic-pathname
           #:tracy-capture-diagnostic-condition
           #:tracy-capture-diagnostic-timestamp
           #:tracy-capture-controller
           #:make-tracy-capture-controller
           #:tracy-capture-application-name
           #:tracy-capture-state
           #:tracy-capture-active-p
           #:tracy-capture-controller-released-p
           #:tracy-capture-pathname
           #:tracy-capture-last-completed-pathname
           #:tracy-capture-diagnostics
           #:tracy-capture-last-diagnostic
           #:start-tracy-capture
           #:stop-tracy-capture
           #:toggle-tracy-capture
           #:open-tracy-capture
           #:reveal-tracy-capture
           #:release-tracy-capture-controller))
