(defpackage #:luv.arithmetic
  (:use #:cl)
  (:documentation
   "Semantic specifications and dimensional algebra for compiled arithmetic.")
  (:export #:dot
           #:dimension
           #:dimension-factors
           #:make-dimension
           #:dimension=
           #:dimensionless-p
           #:multiply-dimensions
           #:divide-dimensions
           #:exponentiate-dimension
           #:unit-definition
           #:unit-definition-name
           #:unit-definition-dimension
           #:unit-definition-magnitude
           #:unit-definition-basis
           #:unit-definition-identity-p
           #:unit-definition-for
           #:define-unit
           #:undefined-unit
           #:undefined-unit-name
           #:unit-expression
           #:unit-expression-factors
           #:make-unit-expression
           #:unit-expression=
           #:unitless-p
           #:unit-expression-dimension
           #:unit-expression-magnitude
           #:unit-expression-basis
           #:unit-conversion-factor
           #:multiply-unit-expressions
           #:divide-unit-expressions
           #:quantity-specification
           #:make-quantity-specification
           #:quantity-specification-name
           #:quantity-specification-dimension
           #:quantity-specification-unit
           #:quantity-specification-tensor-order
           #:quantity-specification-affine-p
           #:quantity-specification=
           #:quantity-projection
           #:make-quantity-projection
           #:quantity-projection-positions
           #:quantity-projection-specification
           #:quantity-layout
           #:make-quantity-layout
           #:quantity-layout-extent
           #:quantity-layout-projections
           #:quantity-layout=
           #:project-quantity-layout
           #:quantity-component-names
           #:define-quantity-components
           #:project-quantity-specification
           #:quantity-operation-error
           #:quantity-operation-error-operator
           #:quantity-operation-error-specifications
           #:quantity-operation-error-reason
           #:interpret-quantity-specification
           #:convert-quantity-specification-unit
           #:derive-quantity-specification))
