(defpackage #:luv.invocation
  (:use #:cl)
  (:documentation
   "A general protocol for reifying the calls of an API as objects, the
way the condition system reifies situations.  Each entry point is a class
of invocations; INVOKE dispatches on both the invoker and the invocation.")
  (:export #:invocation-class
           #:invocation-class-arguments
           #:invocation
           #:invocation-name
           #:invocation-arguments
           #:invocation-sequence
           #:invocation-timestamp
           #:invocation-duration
           #:invocation-thread
           #:invocation-values
           #:invocation-status
           #:invocation-condition
           #:invoker
           #:invoke
           #:snapshot-invocation-value
           #:snapshot-invocation-arguments
           #:invocation-trace
           #:make-invocation-trace
           #:stop-invocation-trace
           #:invocation-trace-events
           #:tracing-invoker
           #:tracing-invoker-trace))

(defpackage #:luv.vk
  (:nicknames #:vk)
  (:use)
  (:documentation
   "The Vulkan entry points luv speaks, one external symbol per foreign
function.  Each symbol names both the class of that function's invocations
and the function that performs one.  DEFVKFUN interns and exports here;
nothing else does."))

(defpackage #:luv.vulkan
  (:nicknames #:lvk)
  (:use #:cl #:luv.invocation)
  (:export #:+portability-enumeration-extension-name+
           #:+swapchain-extension-name+
           #:+debug-utils-extension-name+
           #:vulkan-call-error
           #:vulkan-call-error-operation
           #:vulkan-call-error-result
           #:vulkan-ffi
           #:*vulkan-ffi*
           #:invoke
           #:tracing-ffi
           #:vulkan-invocation
           #:vulkan-command
           #:invocation-sequence
           #:invocation-timestamp
           #:invocation-duration
           #:invocation-thread
           #:invocation-name
           #:invocation-foreign-name
           #:invocation-arguments
           #:invocation-values
           #:invocation-status
           #:invocation-condition
           #:invocation-trace
           #:invocation-trace-events
           #:start-vulkan-trace
           #:stop-vulkan-trace
           #:current-vulkan-trace
           #:with-vulkan-trace
           #:vulkan-trace-presentation-intervals
           #:vulkan-function-description
           #:make-version
           #:enumerate-instance-extension-names
           #:create-instance
           #:destroy-instance
           #:debug-message
           #:debug-message-severity
           #:debug-message-types
           #:debug-message-id-name
           #:debug-message-id-number
           #:debug-message-text
           #:debug-messenger
           #:debug-messenger-destroyed-p
           #:install-debug-messenger
           #:destroy-debug-messenger
           #:enumerate-physical-devices
           #:queue-family
           #:queue-family-flags
           #:queue-family-count
           #:physical-device-queue-families
           #:physical-memory-type
           #:physical-memory-type-flags
           #:physical-memory-type-heap-index
           #:physical-device-memory-types
           #:create-device
           #:destroy-device
           #:get-device-queue
           #:device-wait-idle
           #:create-image
           #:destroy-image
           #:image-memory-requirements
           #:image-memory-requirements-size
           #:image-memory-requirements-alignment
           #:image-memory-requirements-memory-type-bits
           #:get-image-memory-requirements
           #:create-buffer
           #:destroy-buffer
           #:buffer-memory-requirements
           #:buffer-memory-requirements-size
           #:buffer-memory-requirements-alignment
           #:buffer-memory-requirements-memory-type-bits
           #:get-buffer-memory-requirements
           #:allocate-memory
           #:free-memory
           #:bind-image-memory
           #:bind-buffer-memory
           #:map-memory
           #:unmap-memory
           #:create-image-view
           #:destroy-image-view
           #:create-shader-module
           #:destroy-shader-module
           #:create-storage-image-descriptor-set-layout
           #:create-uniform-buffer-descriptor-set-layout
           #:create-texture-sampler-uniform-descriptor-set-layout
           #:destroy-descriptor-set-layout
           #:create-pipeline-layout
           #:destroy-pipeline-layout
           #:create-compute-pipeline
           #:create-graphics-pipeline
           #:destroy-pipeline
           #:create-sampler
           #:destroy-sampler
           #:create-color-render-pass
           #:create-depth-render-pass
           #:destroy-render-pass
           #:create-framebuffer
           #:destroy-framebuffer
           #:create-storage-image-descriptor-pool
           #:create-uniform-buffer-descriptor-pool
           #:create-texture-sampler-uniform-descriptor-pool
           #:destroy-descriptor-pool
           #:allocate-descriptor-set
           #:update-storage-image-descriptor
           #:update-uniform-buffer-descriptor
           #:update-texture-sampler-uniform-descriptors
           #:create-command-pool
           #:destroy-command-pool
           #:allocate-command-buffer
           #:begin-command-buffer
           #:end-command-buffer
           #:cmd-transition-image
           #:cmd-clear-color-image
           #:cmd-copy-image
           #:cmd-copy-buffer-to-image
           #:cmd-copy-image-to-buffer
           #:cmd-bind-compute-pipeline
           #:cmd-bind-graphics-pipeline
           #:cmd-bind-compute-descriptor-set
           #:cmd-bind-graphics-descriptor-set
           #:cmd-bind-vertex-buffer
           #:cmd-dispatch
           #:cmd-begin-color-render-pass
           #:cmd-begin-depth-render-pass
           #:cmd-set-viewport-and-scissor
           #:cmd-end-render-pass
           #:cmd-draw
           #:submit-command-buffers
           #:submit-command-buffer
           #:queue-wait-idle
           #:surface-supported-p
           #:presentation-capabilities
           #:presentation-capabilities-min-image-count
           #:presentation-capabilities-max-image-count
           #:presentation-capabilities-current-extent
           #:presentation-capabilities-min-image-extent
           #:presentation-capabilities-max-image-extent
           #:presentation-capabilities-current-transform
           #:presentation-capabilities-composite-alpha
           #:presentation-capabilities-usage
           #:get-surface-capabilities
           #:presentation-format
           #:presentation-format-format
           #:presentation-format-color-space
           #:get-surface-formats
           #:get-surface-present-modes
           #:create-swapchain
           #:destroy-swapchain
           #:get-swapchain-images
           #:create-semaphore
           #:create-timeline-semaphore
           #:destroy-semaphore
           #:semaphore-counter-value
           #:wait-semaphore-value
           #:acquire-next-image
           #:present))

;;; LUV remains the REPL-friendly public facade.  ASDF systems now separate
;;; the GPU API, Vulkan binding layers, backend, canvas host/presentation, and
;;; examples without forcing a package migration on current callers.

(defpackage #:luv
  (:use #:cl)
  (:export #:*gpu-provider*
           #:gpu-error
           #:gpu-error-operation
           #:gpu-request-error
           #:gpu-request-error-descriptor
           #:gpu-request-error-reason
           #:gpu-request-error-details
           #:gpu-object-error
           #:gpu-object-error-object
           #:gpu-object-destroyed-error
           #:gpu-invalid-state-error
           #:gpu-invalid-state-error-state
           #:gpu-invalid-state-error-expected-state
           #:gpu-device-mismatch-error
           #:gpu-device-mismatch-error-expected-device
           #:gpu-device-mismatch-error-actual-device
           #:gpu-usage-error
           #:gpu-usage-error-required-usage
           #:gpu-usage-error-actual-usage
           #:gpu-resource-leaked
           #:gpu-resource-leaked-class
           #:gpu-resource-leaked-label
           #:*leaked-gpu-resources*
           #:vulkan-gpu-error
           #:vulkan-gpu-error-reason
           #:vulkan-gpu-error-details
           #:gpu-provider
           #:gpu-device
           #:gpu-queue
           #:gpu-buffer
           #:gpu-buffer-size
           #:gpu-buffer-usage
           #:gpu-texture
           #:gpu-texture-size
           #:gpu-texture-usage
           #:gpu-texture-dimensions
           #:gpu-texture-format
           #:gpu-texture-view
           #:gpu-texture-view-texture
           #:gpu-sampler
           #:gpu-shader-module
           #:gpu-bind-group-layout
           #:gpu-bind-group
           #:gpu-compute-pipeline
           #:gpu-render-pipeline
           #:gpu-encoder
           #:gpu-render-pass-encoder
           #:gpu-compute-pass-encoder
           #:gpu-command-encoder
           #:gpu-command-buffer
           #:gpu-command
           #:gpu-queue-command
           #:gpu-command-encoder-command
           #:gpu-pass-command
           #:gpu-render-pass-command
           #:gpu-compute-pass-command
           #:gpu-draw-command
           #:gpu-set-pipeline-command
           #:gpu-set-bind-group-command
           #:gpu-set-vertex-buffer-command
           #:gpu-dispatch-workgroups-command
           #:gpu-clear-texture-command
           #:gpu-copy-texture-command
           #:gpu-copy-texture-to-buffer-command
           #:gpu-write-texture-command
           #:gpu-object-label
           #:request-gpu-device
           #:device-queue
           #:create
           #:encode
           #:enqueue
           #:finish
           #:submit
           #:submitted-work-done
           #:write-buffer
           #:read-buffer
           #:write-texture
           #:destroy
           #:begin-compute-pass
           #:begin-render-pass
           #:end-pass
           #:set-pipeline
           #:set-bind-group
           #:set-vertex-buffer
           #:dispatch-workgroups
           #:draw
           #:make-device-descriptor
           #:make-buffer-descriptor
           #:make-texture-descriptor
           #:make-texture-copy
           #:texture-copy-texture
           #:texture-copy-mip-level
           #:texture-copy-origin
           #:texture-copy-aspect
           #:make-texture-data-layout
           #:texture-data-layout-offset
           #:texture-data-layout-bytes-per-row
           #:texture-data-layout-rows-per-image
           #:make-texture-view-descriptor
           #:make-sampler-descriptor
           #:make-shader-module-descriptor
           #:make-bind-group-layout-descriptor
           #:make-bind-group-descriptor
           #:make-compute-pipeline-descriptor
           #:make-render-pipeline-descriptor
           #:make-render-pass-descriptor
           #:make-command-encoder-descriptor
           #:make-gpu-clear-texture-command
           #:make-gpu-copy-texture-command
           #:make-gpu-copy-texture-to-buffer-command
           #:make-gpu-write-texture-command
           #:make-gpu-set-pipeline-command
           #:make-gpu-set-bind-group-command
           #:make-gpu-set-vertex-buffer-command
           #:make-gpu-dispatch-workgroups-command
           #:make-gpu-draw-command
           #:vulkan-gpu-provider
           #:vulkan-provider-application-name
           #:vulkan-provider-debug-callback
           #:vulkan-provider-debug-severities
           #:vulkan-provider-debug-types
           #:vulkan-device-instance-extension-names
           #:vulkan-device-debug-messenger
           #:canvas-clock
           #:canvas-event-handler
           #:canvas-event
           #:canvas-event-timestamp
           #:canvas-pointer-event
           #:canvas-pointer-event-x
           #:canvas-pointer-event-y
           #:canvas-pointer-event-delta-x
           #:canvas-pointer-event-delta-y
           #:canvas-pointer-motion-event
           #:canvas-pointer-enter-event
           #:canvas-pointer-exit-event
           #:canvas-pointer-button-event
           #:canvas-pointer-event-button
           #:canvas-pointer-event-clicks
           #:canvas-pointer-button-press-event
           #:canvas-pointer-button-release-event
           #:canvas-key-event
           #:canvas-key-event-key-name
           #:canvas-key-event-modifiers
           #:canvas-key-event-character
           #:canvas-key-event-repeat-p
           #:canvas-key-press-event
           #:canvas-key-release-event
           #:canvas-window-event
           #:canvas-window-size-event
           #:canvas-window-event-width
           #:canvas-window-event-height
           #:canvas-window-resized-event
           #:canvas-window-pixel-size-changed-event
           #:canvas-window-focus-gained-event
           #:canvas-window-focus-lost-event
           #:canvas-window-close-request-event
           #:handle-canvas-event
           #:demand-clock
           #:cadence-clock
           #:make-demand-clock
           #:make-cadence-clock
           #:clock-frames-per-second
           #:clock-frame-function
           #:clock-wait-timeout
           #:service-canvas-clock
           #:canvas
           #:canvas-context
           #:context-canvas
           #:context-device
           #:canvas-error
           #:canvas-error-canvas
           #:canvas-error-operation
           #:canvas-error-reason
           #:canvas-error-details
           #:canvas-state-error
           #:canvas-state-error-state
           #:canvas-state-error-expected-state
           #:canvas-configuration
           #:make-canvas-configuration
           #:canvas-configuration-device
           #:canvas-configuration-format
           #:canvas-configuration-usage
           #:get-current-texture
           #:sdl-canvas
           #:make-sdl-canvas
           #:vulkan-canvas-context
           #:canvas-title
           #:canvas-width
           #:canvas-height
           #:canvas-size
           #:canvas-logical-size
           #:canvas-position
           #:canvas-visible-p
           #:set-canvas-relative-pointer-mode
           #:show-canvas
           #:hide-canvas
           #:move-canvas
           #:resize-canvas
           #:raise-canvas
           #:minimize-canvas
           #:restore-canvas
           #:write-rgba-png
           #:world-coordinate
           #:make-world-coordinate
           #:world-coordinate-x
           #:world-coordinate-y
           #:world-coordinate-z
           #:chunk-coordinate
           #:make-chunk-coordinate
           #:chunk-coordinate-x
           #:chunk-coordinate-y
           #:chunk-coordinate-z
           #:local-coordinate
           #:make-local-coordinate
           #:local-coordinate-x
           #:local-coordinate-y
           #:local-coordinate-z
           #:chunk-shape
           #:make-chunk-shape
           #:chunk-shape-width
           #:chunk-shape-height
           #:chunk-shape-depth
           #:voxel-space
           #:make-voxel-space
           #:voxel-space-id
           #:voxel-space-chunk-shape
           #:voxel-space-cell-extent
           #:world-coordinate-cell-origin
           #:world-coordinate-chunk-and-local
           #:chunk-local-world-coordinate
           #:chunk-domain
           #:make-chunk-domain
           #:chunk-domain-space
           #:chunk-domain-coordinate
           #:chunk-domain-cardinality
           #:chunk-domain-origin
           #:chunk-domain-local-coordinate-p
           #:chunk-domain-offset
           #:chunk-domain-local-coordinate
           #:block-content-column
           #:block-content-column-palette
           #:block-content-column-indices
           #:borrow-block-content-storage
           #:with-block-content-storage
           #:block-chunk
           #:make-block-chunk
           #:block-chunk-domain
           #:block-chunk-content
           #:block-chunk-incarnation
           #:block-chunk-revision
           #:block-chunk-boundary-revision
           #:chunk-block-at
           #:chunk-block-at-offset
           #:map-chunk-blocks
           #:block-kind
           #:block-kind-name
           #:block-kind-face-tiles
           #:*crystal-block*
           #:block-solid-p
           #:block-face-tile
           #:block-face
           #:block-face-name
           #:block-face-neighbor
           #:block-face-corners
           #:block-world
           #:block-world-space
           #:block-world-source
           #:block-world-revision
           #:block-world-residency-revision
           #:call-with-world-change-transaction
           #:with-world-change-transaction
           #:make-block-world
           #:world-chunk-at
           #:ensure-world-chunk
           #:install-world-chunk-storage
           #:remove-world-chunk
           #:resident-world-chunks
           #:chunk-not-resident
           #:block-ray-hit
           #:block-ray-hit-coordinate
           #:block-ray-hit-adjacent-coordinate
           #:block-ray-hit-block
           #:block-ray-hit-distance
           #:raycast-block-world
           #:little-world-source
           #:little-world-source-seed
           #:little-world-source-edits
           #:little-world-value-noise
           #:little-world-surface-height
           #:little-world-surface-material
           #:materialize-block-world-chunk
           #:populate-block-world-chunk
           #:apply-block-world-source-edits
           #:edit-block-world-source
           #:maintain-block-world-residency
           #:make-block-chunk-load-request
           #:block-chunk-load-request
           #:block-chunk-load-payload
           #:center-little-world-residency
           #:materialize-little-world-chunk
           #:populate-little-world-chunk
           #:rematerialize-little-world-chunk
           #:make-little-block-world
           #:make-empty-little-block-world
           #:world-block-at
           #:edit-block-at
           #:block-edit-overlay
           #:make-block-edit-overlay
           #:block-edit-overlay-count
           #:record-block-edit
           #:block-edit-at
           #:apply-block-edits-to-chunk
           #:block-mesher
           #:exposed-face-mesher
           #:block-mesh
           #:block-mesh-vertices
           #:block-mesh-vertex-count
           #:block-mesh-face-count
           #:block-mesh-snapshot
           #:block-mesh-snapshot-key
           #:block-mesh-snapshot-dependency-stamp
           #:make-block-mesh-snapshot
           #:mesh-block-world
           #:mesh-block-chunk
           #:mesh-block-snapshot
           #:chunk-mesh-dependency-stamp
           #:emit-block-face
           #:block-light-opacity
           #:block-light-emission
           #:block-surface-emission
           #:chunk-light-field
           #:chunk-light-field-sky-levels
           #:chunk-light-field-block-levels
           #:chunk-light-field-revision
           #:chunk-light-field-boundary-revision
           #:chunk-light-field-state
           #:block-chunk-light-field
           #:absent-chunk-light-semantics
           #:relight-block-world
           #:chunk-light-levels-at
           #:world-light-at
           #:luvcraft-lighting-state
           #:attach-lighting-state
           #:reconcile-lighting
           #:lighting-state-world
           #:lighting-state-cells-visited
           #:lighting-state-chunks-touched
           #:lighting-state-publications
           #:lighting-state-last-latency-seconds
           #:sample-light-at
           #:make-block-texture-atlas
           #:placeable-block-kinds
           #:fly-camera
           #:camera-x
           #:camera-y
           #:camera-z
           #:camera-yaw
           #:camera-pitch
           #:camera-basis
           #:camera-uniform-data
           #:sky-clock
           #:sky-clock-day-fraction
           #:sky-clock-rate
           #:sky-clock-paused-p
           #:sky-clock-pinned-day-fraction
           #:advance-sky-clock
           #:sky-keyframe
           #:make-sky-keyframe
           #:sky-profile
           #:make-sky-profile
           #:make-default-sky-profile
           #:sky-frame-parameters
           #:frame-uniform-data
           #:block-world-player
           #:player-x
           #:player-y
           #:player-z
           #:player-velocity-x
           #:player-velocity-y
           #:player-velocity-z
           #:player-half-width
           #:player-height
           #:player-eye-height
           #:player-grounded-p
           #:make-player-for-camera
           #:sync-camera-to-player
           #:step-block-world-player
           #:luvcraft-session
           #:luvcraft-session-canvas
           #:luvcraft-session-world
           #:luvcraft-session-production-system
           #:luvcraft-session-desired-chunks
           #:luvcraft-session-outstanding-production
           #:luvcraft-session-production-errors
           #:luvcraft-session-mesh
           #:luvcraft-session-chunk-products
           #:luvcraft-chunk-product
           #:luvcraft-chunk-product-coordinate
           #:luvcraft-chunk-product-dependency-stamp
           #:luvcraft-chunk-product-mesh
           #:luvcraft-session-camera
           #:luvcraft-session-player
           #:luvcraft-session-residency-radius
           #:luvcraft-session-residency-center
           #:maintain-luvcraft-residency
           #:luvcraft-session-selected-block
           #:select-luvcraft-block
           #:pick-luvcraft-block
           #:luvcraft-session-atlas-texture
           #:luvcraft-session-atlas-view
           #:luvcraft-session-atlas-sampler
           #:luvcraft-session-shadow-depth-texture
           #:luvcraft-session-shadow-depth-view
           #:luvcraft-session-shadow-depth-sampler
           #:luvcraft-session-meshed-world-revision
           #:luvcraft-session-target
           #:edit-luvcraft-block
           #:refresh-luvcraft-mesh
           #:wait-for-luvcraft-products
           #:luvcraft-session-running-p
           #:live-shader-pipeline
           #:live-shader-pipeline-role
           #:live-shader-pipeline-stage
           #:live-shader-pipeline-vertex-role
           #:live-shader-pipeline-vertex-specification
           #:live-shader-pipeline-vertex-lowering
           #:live-shader-pipeline-specification
           #:live-shader-pipeline-lowering
           #:live-shader-pipeline-status
           #:live-shader-pipeline-diagnostic
           #:live-shader-pipeline-installed-revision
           #:luvcraft-session-block-pipeline
           #:luvcraft-session-shadow-pipeline
           #:luvcraft-session-lighting-state
           #:luvcraft-session-sky-pipeline
           #:luvcraft-session-sky-clock
           #:luvcraft-session-sky-profile
           #:luvcraft-session-crosshair-pipeline
           #:refresh-luvcraft-shaders
           #:start-luvcraft
           #:stop-luvcraft
           #:capture-luvcraft-screenshot
           #:capture-hidden-luvcraft-screenshot
           #:capture-hidden-luvcraft-frames
           #:luvcraft-gazetteer-view
           #:luvcraft-gazetteer-view-name
           #:luvcraft-gazetteer-view-description
           #:luvcraft-gazetteer-views
           #:find-luvcraft-gazetteer-view
           #:capture-luvcraft-gazetteer-view
           #:capture-luvcraft-gazetteer
           #:capture-luvcraft-gazetteer-sequence
           #:request-canvas-frame
           #:make-canvas-context
           #:configure-canvas-context
           #:unconfigure-canvas-context
           #:destroy-canvas-context
           #:call-with-canvas-frame
           #:canvas-device
           #:canvas-extent
           #:canvas-format
           #:canvas-state
           #:canvas-context-state
           #:open-canvas
           #:present-canvas-frame
           #:render-canvas-color
           #:clear-color-demo
           #:demo-canvas
           #:demo-context
           #:demo-speed
           #:start-clear-color-demo
           #:stop-clear-color-demo
           #:compute-gradient-demo
           #:start-compute-gradient-demo
           #:stop-compute-gradient-demo
           #:close-canvas))
