(defpackage #:luv.vulkan
  (:nicknames #:lvk)
  (:use #:cl)
  (:export #:+portability-enumeration-extension-name+
           #:+swapchain-extension-name+
           #:vulkan-call-error
           #:vulkan-call-error-result
           #:make-version
           #:enumerate-instance-extension-names
           #:create-instance
           #:destroy-instance
           #:enumerate-physical-devices
           #:queue-family
           #:queue-family-flags
           #:queue-family-count
           #:physical-device-queue-families
           #:physical-memory-type
           #:physical-memory-type-flags
           #:physical-memory-type-heap-index
           #:physical-device-memory-types
           #:create-device
           #:destroy-device
           #:get-device-queue
           #:device-wait-idle
           #:create-image
           #:destroy-image
           #:image-memory-requirements
           #:image-memory-requirements-size
           #:image-memory-requirements-alignment
           #:image-memory-requirements-memory-type-bits
           #:get-image-memory-requirements
           #:allocate-memory
           #:free-memory
           #:bind-image-memory
           #:create-command-pool
           #:destroy-command-pool
           #:allocate-command-buffer
           #:begin-command-buffer
           #:end-command-buffer
           #:cmd-transition-image
           #:cmd-clear-color-image
           #:cmd-copy-image
           #:submit-command-buffers
           #:submit-command-buffer
           #:queue-wait-idle
           #:surface-supported-p
           #:presentation-capabilities
           #:presentation-capabilities-min-image-count
           #:presentation-capabilities-max-image-count
           #:presentation-capabilities-current-extent
           #:presentation-capabilities-min-image-extent
           #:presentation-capabilities-max-image-extent
           #:presentation-capabilities-current-transform
           #:presentation-capabilities-composite-alpha
           #:presentation-capabilities-usage
           #:get-surface-capabilities
           #:presentation-format
           #:presentation-format-format
           #:presentation-format-color-space
           #:get-surface-formats
           #:get-surface-present-modes
           #:create-swapchain
           #:destroy-swapchain
           #:get-swapchain-images
           #:create-semaphore
           #:destroy-semaphore
           #:acquire-next-image
           #:present))

(defpackage #:luv
  (:use #:cl)
  (:export #:*gpu-provider*
           #:gpu-error
           #:gpu-error-operation
           #:gpu-request-error
           #:gpu-request-error-descriptor
           #:gpu-request-error-reason
           #:gpu-request-error-details
           #:gpu-object-error
           #:gpu-object-error-object
           #:gpu-object-destroyed-error
           #:gpu-invalid-state-error
           #:gpu-invalid-state-error-state
           #:gpu-invalid-state-error-expected-state
           #:gpu-device-mismatch-error
           #:gpu-device-mismatch-error-expected-device
           #:gpu-device-mismatch-error-actual-device
           #:gpu-usage-error
           #:gpu-usage-error-required-usage
           #:gpu-usage-error-actual-usage
           #:vulkan-gpu-error
           #:vulkan-gpu-error-reason
           #:vulkan-gpu-error-details
           #:gpu-provider
           #:gpu-device
           #:gpu-queue
           #:gpu-texture
           #:gpu-texture-size
           #:gpu-texture-usage
           #:gpu-texture-dimensions
           #:gpu-texture-format
           #:gpu-command-encoder
           #:gpu-command-buffer
           #:gpu-object-label
           #:request-gpu-device
           #:device-queue
           #:create
           #:encode
           #:finish
           #:submit
           #:destroy
           #:make-device-descriptor
           #:make-texture-descriptor
           #:make-command-encoder-descriptor
           #:make-gpu-clear-texture-command
           #:make-gpu-copy-texture-command
           #:vulkan-gpu-provider
           #:canvas-clock
           #:demand-clock
           #:cadence-clock
           #:make-demand-clock
           #:make-cadence-clock
           #:clock-frames-per-second
           #:clock-frame-function
           #:clock-wait-timeout
           #:service-canvas-clock
           #:canvas
           #:canvas-context
           #:context-canvas
           #:context-device
           #:canvas-error
           #:canvas-error-canvas
           #:canvas-error-operation
           #:canvas-error-reason
           #:canvas-error-details
           #:canvas-state-error
           #:canvas-state-error-state
           #:canvas-state-error-expected-state
           #:canvas-configuration
           #:make-canvas-configuration
           #:canvas-configuration-device
           #:canvas-configuration-format
           #:canvas-configuration-usage
           #:get-current-texture
           #:sdl-canvas
           #:make-sdl-canvas
           #:vulkan-canvas-context
           #:canvas-title
           #:canvas-width
           #:canvas-height
           #:canvas-size
           #:request-canvas-frame
           #:make-canvas-context
           #:configure-canvas-context
           #:unconfigure-canvas-context
           #:destroy-canvas-context
           #:call-with-canvas-frame
           #:canvas-device
           #:canvas-extent
           #:canvas-format
           #:canvas-state
           #:canvas-context-state
           #:open-canvas
           #:present-canvas-frame
           #:render-canvas-color
           #:clear-color-demo
           #:demo-canvas
           #:demo-context
           #:demo-speed
           #:start-clear-color-demo
           #:stop-clear-color-demo
           #:close-canvas))
