(defpackage #:luv.spir-v
  (:nicknames #:spv)
  (:use #:cl)
  (:shadow #:function #:load #:return #:step #:variable)
  (:export #:spir-v-error
           #:spir-v-error-form
           #:spir-v-error-reason
           #:spir-v-error-details
           #:define-instruction
           #:define-enumeration
           #:instruction
           #:instruction-class
           #:instruction-name
           #:instruction-opcode
           #:instruction-result-convention
           #:instruction-result-id
           #:instruction-result-type
           #:instruction-form
           #:parse-instruction
           #:parse-module
           #:assemble
           #:write-spir-v
           #:spir-v-module
           #:spir-v-module-version
           #:spir-v-module-generator
           #:spir-v-module-capabilities
           #:spir-v-module-extensions
           #:spir-v-module-extended-instruction-imports
           #:spir-v-extended-instruction-import
           #:spir-v-extended-instruction-import-result-id
           #:spir-v-extended-instruction-import-name
           #:spir-v-module-addressing-model
           #:spir-v-module-memory-model
           #:spir-v-module-entry-points
           #:spir-v-module-execution-modes
           #:spir-v-module-debug-instructions
           #:spir-v-module-annotations
           #:spir-v-module-global-declarations
           #:spir-v-module-function-definitions
           #:spir-v-entry-point
           #:spir-v-entry-point-execution-model
           #:spir-v-entry-point-function
           #:spir-v-entry-point-name
           #:spir-v-entry-point-interfaces
           #:spir-v-execution-mode
           #:spir-v-execution-mode-function
           #:spir-v-execution-mode-name
           #:spir-v-execution-mode-literals
           #:spir-v-function-definition
           #:spir-v-function-result-id
           #:spir-v-function-return-type
           #:spir-v-function-control
           #:spir-v-function-type
           #:spir-v-function-parameters
           #:spir-v-function-basic-blocks
           #:spir-v-basic-block
           #:spir-v-basic-block-label
           #:spir-v-basic-block-instructions
           #:lower-spir-v
           #:assemble-spir-v-module
           #:shader-language-error
           #:shader-language-error-form
           #:shader-language-error-reason
           #:shader-language-error-details
           #:shader-type
           #:shader-type-name
           #:shader-type-component-count
           #:shader-type-opaque-kind
           #:shader-type-sample-result-type
           #:shader-type-image-depth-p
           #:find-shader-type
           #:shader-type=
           #:shader-object-name
           #:shader-object-source-form
           #:shader-variable-declaration
           #:shader-declaration-type
           #:shader-interface-variable
           #:shader-interface-direction
           #:shader-interface-location
           #:shader-interface-built-in
           #:shader-resource
           #:shader-resource-descriptor-set
           #:shader-resource-binding
           #:shader-uniform-block
           #:shader-uniform-block-members
           #:shader-uniform-block-byte-size
           #:shader-uniform-member
           #:shader-uniform-member-block
           #:shader-uniform-member-index
           #:shader-uniform-member-offset
           #:shader-binding
           #:shader-binding-expression
           #:shader-expression
           #:shader-expression-type
           #:shader-expression-source-form
           #:shader-expression-name
           #:shader-literal
           #:shader-literal-value
           #:shader-reference
           #:shader-reference-target
           #:shader-call
           #:shader-call-operator
           #:shader-call-operands
           #:shader-call-parameters
           #:shader-expression-form
           #:shader-expression-children
           ;; The shader-language vocabulary.  Arithmetic operators are CL's
           ;; own symbols; these are the words CL does not have, plus the
           ;; protocol for defining and implementing new operators.
           #:dot
           #:sample
           #:mix
           #:vec2
           #:vec3
           #:vec4
           #:swizzle
           #:clamp
           #:smoothstep
           #:step
           #:normalize
           #:set-output
           #:shader-operator
           #:define-shader-operator
           #:shader-operator-p
           #:shader-abstraction
           #:define-shader-abstraction
           #:shader-abstraction-p
           #:shader-abstraction-revision
           #:expand-shader-abstraction-call
           #:expand-shader-source-form
           #:shadow-depth-test
           #:shadow-visibility
           #:parse-shader-operator-call
           #:infer-shader-call-type
           #:lower-shader-call
           #:shader-operator-result-name
           #:binary-arithmetic-instruction
           #:shader-output-assignment
           #:shader-assignment-output
           #:shader-assignment-value
           #:shader-assignment-source-form
           #:shader-specification
           #:shader-specification-stage
           #:shader-specification-inputs
           #:shader-specification-outputs
           #:shader-specification-resources
           #:shader-specification-bindings
           #:shader-specification-statements
           #:shader-specification-expressions
           #:define-shader
           #:define-shader-method
           #:shader-specification-for
           #:shader-definition-dependent
           #:make-shader-definition-dependent
           #:shader-definition-dependent-arguments
           #:shader-definition-change-pending-p
           #:shader-definition-change-snapshot
           #:acknowledge-shader-definition-change
           #:release-shader-definition-dependent
           #:parse-shader-specification
           #:compile-shader-specification
           #:shader-lowering
           #:shader-lowering-specification
           #:shader-lowering-module
           #:shader-lowering-expression-instructions
           #:shader-lowering-instruction-expressions
           #:shader-lowering-diagnostics
           #:shader-module
           #:assemble-shader-specification
           #:gradient-compute-module
           #:gradient-compute-shader
           #:spinning-texture-vertex-module
           #:spinning-texture-fragment-module
           #:spinning-texture-vertex-shader
           #:spinning-texture-fragment-shader
           #:block-world-vertex-module
           #:block-world-vertex-specification
           #:block-world-vertex-lowering
           #:block-world-camera-uniform-block
           #:block-world-fragment-specification
           #:block-world-fragment-lowering
           #:block-world-fragment-module
           #:block-world-sky-vertex-specification
           #:block-world-sky-vertex-module
           #:block-world-sky-vertex-shader
           #:block-world-sky-fragment-specification
           #:block-world-sky-fragment-module
           #:block-world-sky-fragment-shader
           #:block-world-shadow-vertex-specification
           #:block-world-shadow-vertex-module
           #:block-world-shadow-vertex-shader
           #:block-world-crosshair-vertex-module
           #:block-world-crosshair-fragment-specification
           #:block-world-crosshair-fragment-module
           #:block-world-vertex-shader
           #:block-world-fragment-shader
           #:block-world-crosshair-vertex-shader
           #:block-world-crosshair-fragment-shader))
