(defpackage #:luvcraft
  (:use #:cl #:luv #:luvcraft.world)
  (:local-nicknames (#:fields #:luvcraft.world.fields)
                    (#:math #:luv.arithmetic)
                    (#:records #:luv.arithmetic.records)
                    (#:spv #:luv.spir-v))
  (:import-from #:luv.arithmetic.lisp.vec3
                #:make-vec3
                #:vec3
                #:vec3-component
                #:vec3-cross
                #:vec3-dot
                #:vec3-list
                #:vec3-normalize
                #:vec3-scale
                #:vec3-x
                #:vec3-y
                #:vec3-z)
  (:documentation "The interactive block world built on luv.")
  (:export #:*crystal-block*
           #:*session*
           #:+little-world-source-version+
           #:+luvcraft-save-format-version+
           #:absent-chunk-light-semantics
           #:add-luvcraft-overlay
           #:advance-sky-clock
           #:apply-block-world-source-edits
           #:attach-lighting-state
           #:benchmark-luvcraft-frame-performance
           #:block-chunk-load-payload
           #:block-chunk-load-request
           #:block-face
           #:block-face-corners
           #:block-face-name
           #:block-face-neighbor
           #:block-face-tile
           #:block-kind
           #:block-kind-face-tiles
           #:block-kind-name
           #:block-kind-named
           #:block-light-emission
           #:block-light-opacity
           #:block-mesh
           #:block-mesh-face-count
           #:block-mesh-snapshot
           #:block-mesh-snapshot-dependency-stamp
           #:block-mesh-snapshot-key
           #:block-mesh-vertex-count
           #:block-mesh-vertex-declaration
           #:block-mesh-vertices
           #:block-mesher
           #:block-particle-count
           #:block-particle-system
           #:block-particle-system-particles
           #:block-save-description
           #:block-solid-p
           #:block-surface-emission
           #:block-world-player
           #:camera-basis
           #:camera-pitch
           #:camera-position
           #:camera-uniform-data
           #:camera-x
           #:camera-y
           #:camera-yaw
           #:camera-z
           #:capture-hidden-luvcraft-frames
           #:capture-hidden-luvcraft-screenshot
           #:capture-luvcraft-gazetteer
           #:capture-luvcraft-gazetteer-sequence
           #:capture-luvcraft-gazetteer-view
           #:capture-luvcraft-screenshot
           #:center-little-world-residency
           #:chunk-light-field
           #:chunk-light-field-block-levels
           #:chunk-light-field-boundary-revision
           #:chunk-light-field-revision
           #:chunk-light-field-sky-levels
           #:chunk-light-field-state
           #:chunk-light-levels-at
           #:chunk-light-levels-at-coordinate
           #:chunk-mesh-dependency-stamp
           #:edit-block-at
           #:edit-block-world-source
           #:edit-luvcraft-block
           #:encode-luvcraft-overlay
           #:handle-luvcraft-overlay-event
           #:emit-block-face
           #:exposed-face-mesher
           #:find-luvcraft-gazetteer-view
           #:fly-camera
           #:frame-uniform-data
           #:invalid-luvcraft-save
           #:invalid-luvcraft-save-reason
           #:lighting-state-cells-visited
           #:lighting-state-chunks-touched
           #:lighting-state-last-latency-seconds
           #:lighting-state-publications
           #:lighting-state-world
           #:little-world-source
           #:little-world-source-edits
           #:little-world-source-seed
           #:little-world-surface-height
           #:little-world-surface-material
           #:little-world-value-noise
           #:live-shader-pipeline
           #:live-shader-pipeline-diagnostic
           #:live-shader-pipeline-installed-revision
           #:live-shader-pipeline-lowering
           #:live-shader-pipeline-role
           #:live-shader-pipeline-specification
           #:live-shader-pipeline-stage
           #:live-shader-pipeline-status
           #:live-shader-pipeline-vertex-lowering
           #:live-shader-pipeline-vertex-role
           #:live-shader-pipeline-vertex-specification
           #:luvcraft-chunk-product
           #:luvcraft-chunk-product-coordinate
           #:luvcraft-chunk-product-dependency-stamp
           #:luvcraft-chunk-product-mesh
           #:luvcraft-frame-benchmark
           #:luvcraft-frame-benchmark-completion-seconds
           #:luvcraft-frame-benchmark-samples
           #:luvcraft-gazetteer-view
           #:luvcraft-gazetteer-view-description
           #:luvcraft-gazetteer-view-name
           #:luvcraft-gazetteer-views
           #:luvcraft-lighting-state
           #:luvcraft-session
           #:luvcraft-session-atlas-sampler
           #:luvcraft-session-atlas-texture
           #:luvcraft-session-atlas-view
           #:luvcraft-session-block-pipeline
           #:luvcraft-session-camera
           #:luvcraft-session-canvas
           #:luvcraft-session-checkpoint-writer
           #:luvcraft-session-chunk-products
           #:luvcraft-session-crosshair-pipeline
           #:luvcraft-session-desired-chunks
           #:luvcraft-session-lighting-state
           #:luvcraft-session-mesh
           #:luvcraft-session-meshed-world-revision
           #:luvcraft-session-outstanding-production
           #:luvcraft-session-overlays
           #:luvcraft-session-particle-system
           #:luvcraft-session-player
           #:luvcraft-session-production-errors
           #:luvcraft-session-production-system
           #:luvcraft-session-residency-center
           #:luvcraft-session-residency-radius
           #:luvcraft-session-running-p
           #:luvcraft-session-selected-block
           #:luvcraft-session-shadow-comparison-sampler
           #:luvcraft-session-shadow-depth-sampler
           #:luvcraft-session-shadow-depth-texture
           #:luvcraft-session-shadow-depth-view
           #:luvcraft-session-shadow-pipeline
           #:luvcraft-session-sky-clock
           #:luvcraft-session-sky-pipeline
           #:luvcraft-session-sky-profile
           #:luvcraft-session-target
           #:luvcraft-session-world
           #:main
           #:maintain-block-world-residency
           #:maintain-luvcraft-residency
           #:make-block-chunk-load-request
           #:make-block-mesh-snapshot
           #:make-block-texture-atlas
           #:make-default-sky-profile
           #:make-empty-little-block-world
           #:make-little-block-world
           #:make-luvcraft-save-description
           #:make-player-for-camera
           #:make-sky-keyframe
           #:make-sky-profile
           #:make-world-checkpoint-writer
           #:materialize-block-world-chunk
           #:materialize-little-world-chunk
           #:mesh-block-chunk
           #:mesh-block-snapshot
           #:mesh-block-world
           #:perform-world-checkpoint
           #:pick-luvcraft-block
           #:placeable-block-kinds
           #:player-eye-height
           #:player-grounded-p
           #:player-half-width
           #:player-height
           #:player-position
           #:player-velocity
           #:player-velocity-x
           #:player-velocity-y
           #:player-velocity-z
           #:player-x
           #:player-y
           #:player-z
           #:populate-block-world-chunk
           #:populate-little-world-chunk
           #:print-luvcraft-frame-benchmark
           #:read-luvcraft-save
           #:release-luvcraft-overlay
           #:reconcile-lighting
           #:refresh-luvcraft-mesh
           #:wait-for-luvcraft-streaming-quiescence
           #:trace-luvcraft-streaming-boundary
           #:refresh-luvcraft-shaders
           #:relight-block-world
           #:rematerialize-little-world-chunk
           #:request-luvcraft-session-checkpoint
           #:request-world-checkpoint
           #:remove-luvcraft-overlay
           #:restore-block-save-description
           #:restore-luvcraft-resume-save-description
           #:restore-luvcraft-save-description
           #:restore-world-save-description
           #:restore-world-source-save-description
           #:sample-light-at
           #:select-luvcraft-block
           #:smash-block-particles
           #:sky-clock
           #:sky-clock-day-fraction
           #:sky-clock-paused-p
           #:sky-clock-pinned-day-fraction
           #:sky-clock-rate
           #:sky-frame-parameters
           #:sky-keyframe
           #:sky-profile
           #:start-luvcraft
           #:start-luvcraft-tracy
           #:step-block-world-player
           #:stop-luvcraft
           #:stop-world-checkpoint-writer
           #:sync-camera-to-player
           #:wait-for-luvcraft-products
           #:world-checkpoint-writer
           #:world-checkpoint-writer-condition
           #:world-checkpoint-writer-pathname
           #:world-light-at
           #:world-light-at-coordinate
           #:world-save-description
           #:world-source-save-description
           #:write-luvcraft-frame-benchmark-csv
           #:write-luvcraft-save-description))

(defpackage #:luvcraft.shaders
  (:use #:cl #:luv.spir-v)
  (:shadowing-import-from #:luv.spir-v #:step)
  (:documentation "Luvcraft's hot-replaceable mathematical shader definitions.")
  (:export #:block-world-crosshair-fragment-module
           #:block-world-crosshair-fragment-shader
           #:block-world-crosshair-fragment-specification
           #:block-world-crosshair-vertex-module
           #:block-world-crosshair-vertex-shader
           #:block-world-crosshair-vertex-specification
           #:block-world-fragment-lowering
           #:block-world-fragment-module
           #:block-world-fragment-shader
           #:block-world-fragment-specification
           #:block-world-camera-uniform-block
           #:block-world-shadow-vertex-module
           #:block-world-shadow-vertex-shader
           #:block-world-shadow-vertex-specification
           #:block-world-sky-fragment-module
           #:block-world-sky-fragment-shader
           #:block-world-sky-fragment-specification
           #:block-world-sky-vertex-module
           #:block-world-sky-vertex-shader
           #:block-world-sky-vertex-specification
           #:block-world-text-fragment-specification
           #:block-world-text-vertex-specification
           #:block-world-vertex-lowering
           #:block-world-vertex-module
           #:block-world-vertex-shader
           #:block-world-vertex-specification))
