(in-package #:luft.web)

(defun core-form ()
  '(progn
    ;; ParenScript clears this register on returns; ES modules are strict.
    (defvar ps::|__ps_mv_reg| (array))
    (defvar cells (new (|Map|)))
    (defun cell-key (x y z) (+ x "," y "," z))
    (defun cell-at (x y z) (or ((@ cells get) (cell-key x y z)) 0))
    (defun sample-cell (x y z sample)
      (cell-at (+ x (if (logand sample 1) 0 -1))
               (+ y (if (logand sample 2) 0 -1))
               (+ z (if (logand sample 4) 0 -1))))
    (defun reset-cells ()
      ((@ cells clear))
      ((@ initial-cells for-each)
       (lambda (cell)
         ((@ cells set) (cell-key (aref cell 0) (aref cell 1) (aref cell 2))
                        (aref cell 3)))))
    (defun surface-sites ()
      (let ((sites (new (|Map|))))
        ((@ cells for-each)
         (lambda (kind key)
           (let ((point ((@ (chain key (split ",")) map) |Number|)))
             (dotimes (sample 8)
               (let* ((x (+ (aref point 0) (if (logand sample 1) 0 1)))
                      (y (+ (aref point 1) (if (logand sample 2) 0 1)))
                      (z (+ (aref point 2) (if (logand sample 4) 0 1)))
                      (address (cell-key x y z))
                      (entry ((@ sites get) address)))
                 (unless entry
                   (setf entry (array x y z 0))
                   ((@ sites set) address entry))
                 (setf (aref entry 3) (logior (aref entry 3) (ash 1 sample))))))))
        sites))
    (defun trace-cells (origin direction reach)
      ;; Amanatides-Woo traversal in cell space; returns the solid and the
      ;; preceding air cell, so concave bevels do not confuse edit ownership.
      (let ((cell ((@ origin map) (lambda (v) (floor v))))
            (step (array)) (delta (array)) (next (array))
            (previous null) (distance 0))
        (dotimes (axis 3)
          (let ((d (aref direction axis)) (p (aref origin axis)))
            ((@ step push) (if (> d 0) 1 -1))
            ((@ delta push) (if (= d 0) |Infinity| (abs (/ 1 d))))
            ((@ next push)
             (if (= d 0) |Infinity|
                 (/ (- (+ (aref cell axis) (if (> d 0) 1 0)) p) d)))))
        (while (<= distance reach)
          (when (cell-at (aref cell 0) (aref cell 1) (aref cell 2))
            (return-from trace-cells (create :cell cell :previous previous)))
          (setf previous ((@ cell slice)))
          (let ((axis (if (< (aref next 0) (aref next 1)) 0 1)))
            (when (< (aref next 2) (aref next axis)) (setf axis 2))
            (setf distance (aref next axis))
            (incf (aref next axis) (aref delta axis))
            (incf (aref cell axis) (aref step axis))))
        null))
    (defun collides (x y feet)
      (loop for ix from (floor (- x 0.28)) to (floor (+ x 0.28)) do
        (loop for iy from (floor (- y 0.28)) to (floor (+ y 0.28)) do
          (loop for iz from (floor (+ feet 0.001)) to (floor (+ feet 1.7)) do
            (when (cell-at ix iy iz) (return-from collides true)))))
      false)))
