(in-package #:luft.web)

(defun meshing-form ()
  '(progn
    (defun cell-tone (kind up)
      (let ((side (aref (array (array 0 0 0) (array .42 .32 .21)
                               (array .53 .49 .39) (array .23 .13 .065)
                               (array .16 .68 .94) (array .085 .19 .045)) kind))
            (top (aref (array (array 0 0 0) (array .18 .31 .105)
                              (array .53 .49 .39) (array .23 .13 .065)
                              (array .16 .68 .94) (array .22 .37 .085)) kind)))
        ((@ side map) (lambda (value axis)
                       (+ (* value (- 1 up)) (* (aref top axis) up))))))
    ;; Shared templates are prepared once. Chunk products expand their exact
    ;; triangles into one draw, rather than one draw per star per chunk.
    (defvar mesh-templates
      ((@ atlas map)
       (lambda (entry)
         ((@ (aref entry 0) map)
          (lambda (triangle index)
            (let* ((a (aref triangle 0)) (b (aref triangle 1)) (c (aref triangle 2))
                   (u ((@ b map) (lambda (v axis) (- v (aref a axis)))))
                   (v ((@ c map) (lambda (n axis) (- n (aref a axis)))))
                   (normal (array (- (* (aref u 1) (aref v 2)) (* (aref u 2) (aref v 1)))
                                  (- (* (aref u 2) (aref v 0)) (* (aref u 0) (aref v 2)))
                                  (- (* (aref u 0) (aref v 1)) (* (aref u 1) (aref v 0)))))
                   (length ((@ |Math| hypot) (aref normal 0) (aref normal 1) (aref normal 2)))
                   (unit ((@ normal map) (lambda (n) (/ n length))))
                   (tones ((@ (array 0 1 2 3 4 5) map)
                           (lambda (kind) (cell-tone kind (max 0 (aref unit 2)))))))
              (create :points triangle :normal unit :tones tones
                      :mask (aref (aref (aref entry 1) index) 0))))))))
    (defun mesh-data (sites sampler)
      (let ((count 0) (offset 0))
        ((@ sites for-each)
         (lambda (site) (incf count (* 9 (@ (aref mesh-templates (aref site 3)) length)))))
        (let ((positions (new (|Float32Array| count)))
              ;; Normalized bytes halve resident CPU/GPU mesh storage without
              ;; changing any positions or triangles (this is not LOD).
              (normals (new (|Int8Array| count)))
              (colors (new (|Uint8Array| count))))
          ((@ sites for-each)
           (lambda (site)
             (let ((kinds (array)))
               (dotimes (sample 8)
                 ((@ kinds push)
                  (sampler (+ (aref site 0) (if (logand sample 1) 0 -1))
                           (+ (aref site 1) (if (logand sample 2) 0 -1))
                           (+ (aref site 2) (if (logand sample 4) 0 -1)))))
               ((@ (aref mesh-templates (aref site 3)) for-each)
                (lambda (triangle)
                  (let ((tone (array 0 0 0)) (samples 0))
                    (dotimes (sample 8)
                      (when (logand (@ triangle mask) (ash 1 sample))
                        (incf samples)
                        (dotimes (axis 3)
                          (incf (aref tone axis)
                                (aref (aref (@ triangle tones) (aref kinds sample)) axis)))))
                    ((@ (@ triangle points) for-each)
                     (lambda (point)
                       (dotimes (axis 3)
                         (setf (aref positions offset) (+ (aref site axis) (/ (aref point axis) 8))
                               (aref normals offset) (round (* 127 (aref (@ triangle normal) axis)))
                               (aref colors offset) (round (* 255 (/ (aref tone axis) (max samples 1)))))
                         (incf offset))))))))))
          (create :positions positions :normals normals :colors colors))))))
