;;;; Claims about the session: what goes out and what is reported.

(in-package #:mqtt.tests)

(defun connected-session (&rest initargs)
  "A session that has said CONNECT and heard a plain CONNACK."
  (let ((session (apply #'mqtt:make-mqtt-session :client-id "test" initargs)))
    (mqtt:session-begin session)
    (mqtt:drain-session-outbox session)
    (mqtt:session-receive session (hex "20 03 00 00 00"))
    (mqtt:drain-session-events session)
    session))

(defun outbox-hex (session)
  (mapcar #'unhex (mqtt:drain-session-outbox session)))

(defun event-heads (session)
  (mapcar #'first (mqtt:drain-session-events session)))

(define-test connecting
  (let ((session (mqtt:make-mqtt-session :client-id "luv" :keep-alive 30)))
    (true (eq :new (mqtt:session-state session)))
    (mqtt:session-begin session)
    (true (eq :connecting (mqtt:session-state session)))
    (group (context "CONNECT goes out")
      (let ((out (outbox-hex session)))
        (true (= 1 (length out)))
        (true (typep (decoded (first out)) 'mqtt:connect-packet))))
    (group (context "the CONNACK's assigned id and keep alive win")
      (mqtt:session-receive session (hex "20 0c 00 00 09 12 0003 616263 13 000a"))
      (true (mqtt:session-connected-p session))
      (true (equal "abc" (mqtt:session-client-id session)))
      (true (= 10 (mqtt:session-keep-alive session)))
      (true (equal '(:connected) (event-heads session)))
      (true (= 10 (mqtt:session-server-property session :server-keep-alive))))
    (group (context "a second CONNECT is a protocol error")
      (fail (mqtt:session-begin session) 'mqtt:protocol-error)))
  (group (context "a refusal ends the session")
    (let ((session (mqtt:make-mqtt-session)))
      (mqtt:session-begin session)
      (mqtt:session-receive session (hex "20 03 00 87 00"))
      (true (eq :disconnected (mqtt:session-state session)))
      (true (equal '(:refused) (event-heads session)))
      (fail (mqtt:session-publish session "a" "b") 'mqtt:protocol-error))))

(define-test publishing-at-each-qos
  (let ((session (connected-session)))
    (group (context "QoS 0 goes out and nothing is pending")
      (true (null (mqtt:session-publish session "a/b" "hi")))
      (true (equal '("30080003612f62006869") (outbox-hex session))))
    (group (context "QoS 1 takes id 1 and settles on PUBACK")
      (let ((pending (mqtt:session-publish session "a/b" "hi" :qos 1)))
        (true (= 1 (mqtt:pending-request-id pending)))
        (true (equal '("320a0003612f620001006869") (outbox-hex session)))
        (mqtt:session-receive session (hex "40 02 0001"))
        (true (mqtt:pending-request-done-p pending))
        (true (not (mqtt:pending-request-failed-p pending)))
        (true (equal '(0) (mqtt:pending-request-reason-codes pending)))
        (true (equal '(:published) (event-heads session)))))
    (group (context "QoS 2 takes id 2, releases on PUBREC, settles on PUBCOMP")
      (let ((pending (mqtt:session-publish session "a/b" "hi" :qos 2)))
        (true (= 2 (mqtt:pending-request-id pending)))
        (outbox-hex session)
        (mqtt:session-receive session (hex "50 02 0002"))
        (true (not (mqtt:pending-request-done-p pending)))
        (true (equal '("62020002") (outbox-hex session)))
        (mqtt:session-receive session (hex "70 02 0002"))
        (true (mqtt:pending-request-done-p pending))
        (true (equal '(:published) (event-heads session)))))
    (group (context "a failing PUBREC settles the request as failed")
      (let ((pending (mqtt:session-publish session "a/b" "hi" :qos 2)))
        (outbox-hex session)
        (mqtt:session-receive session (hex "50 03 0003 87"))
        (true (mqtt:pending-request-done-p pending))
        (true (mqtt:pending-request-failed-p pending))
        (true (null (outbox-hex session)))))
    (group (context "an acknowledgement for nothing is a protocol error")
      (fail (mqtt:session-receive session (hex "40 02 0009")) 'mqtt:protocol-error))))

(define-test receiving-at-each-qos
  (let ((session (connected-session)))
    (group (context "QoS 0 is an event and nothing goes back")
      (mqtt:session-receive session (hex "30080003612f62006869"))
      (let ((events (mqtt:drain-session-events session)))
        (true (equal '(:message) (mapcar #'first events)))
        (true (equal "hi" (mqtt:publish-payload-string (second (first events))))))
      (true (null (outbox-hex session))))
    (group (context "QoS 1 is an event and a PUBACK")
      (mqtt:session-receive session (hex "320a0003612f620005006869"))
      (true (equal '(:message) (event-heads session)))
      (true (equal '("40020005") (outbox-hex session))))
    (group (context "QoS 2 is an event, a PUBREC, then a PUBCOMP on release")
      (mqtt:session-receive session (hex "340a0003612f620006006869"))
      (true (equal '(:message) (event-heads session)))
      (true (equal '("50020006") (outbox-hex session)))
      (group (context "and a duplicate before the release is acknowledged, not delivered")
        (mqtt:session-receive session (hex "3c0a0003612f620006006869"))
        (true (null (event-heads session)))
        (true (equal '("50020006") (outbox-hex session))))
      (mqtt:session-receive session (hex "62 02 0006"))
      (true (equal '("70020006") (outbox-hex session)))
      (true (null (event-heads session))))))

(define-test subscribing
  (let ((session (connected-session)))
    (let ((pending (mqtt:session-subscribe session "a/b" '("c/#" :qos 2))))
      (true (equal '("820f0001000003612f62000003632f2302") (outbox-hex session)))
      (mqtt:session-receive session (hex "90 06 0001 00 00 02 00"))
      (true (mqtt:pending-request-done-p pending))
      (true (equal '(0 2 0) (mqtt:pending-request-reason-codes pending)))
      (true (equal '(:subscribed) (event-heads session))))
    (group (context "a refused filter marks the request failed")
      (let ((pending (mqtt:session-subscribe session "$SYS/#")))
        (outbox-hex session)
        (mqtt:session-receive session (hex "90 04 0002 00 87"))
        (true (mqtt:pending-request-failed-p pending))
        (true (equal (quote (:subscribed)) (event-heads session)))))
    (group (context "unsubscribing")
      (let ((pending (mqtt:session-unsubscribe session "a/b")))
        (true (equal '("a2080003000003612f62") (outbox-hex session)))
        (mqtt:session-receive session (hex "b0 04 0003 00 00"))
        (true (mqtt:pending-request-done-p pending))
        (true (equal '(:unsubscribed) (event-heads session)))))))

(define-test pings-and-goodbyes
  (let ((session (connected-session)))
    (mqtt:session-ping session)
    (true (equal '("c000") (outbox-hex session)))
    (mqtt:session-receive session (hex "d000"))
    (true (equal '(:pong) (event-heads session)))
    (group (context "the server can hang up")
      (mqtt:session-receive session (hex "e0 01 8e"))
      (true (eq :disconnected (mqtt:session-state session)))
      (let ((events (mqtt:drain-session-events session)))
        (true (equal '(:disconnected) (mapcar #'first events)))
        (true (eq :session-taken-over (mqtt:packet-reason (second (first events))))))))
  (group (context "or we can")
    (let ((session (connected-session)))
      (mqtt:session-disconnect session :reason :disconnect-with-will-message)
      (true (equal '("e00104") (outbox-hex session)))
      (true (eq :disconnected (mqtt:session-state session)))))
  (group (context "a client-only packet from the server is a protocol error")
    (let ((session (connected-session)))
      (fail (mqtt:session-receive session (hex "c000")) 'mqtt:protocol-error))))

(define-test packet-ids-skip-those-in-flight
  (let ((session (connected-session)))
    (setf (slot-value session 'mqtt::next-packet-id) 65535)
    (let ((first (mqtt:session-publish session "a" "b" :qos 1))
          (second (mqtt:session-publish session "a" "b" :qos 1)))
      (true (= 65535 (mqtt:pending-request-id first)))
      (true (= 1 (mqtt:pending-request-id second)))
      (mqtt:session-receive session (hex "40 02 0001"))
      (setf (slot-value session 'mqtt::next-packet-id) 65535)
      (group (context "65535 is still busy, so the next id is 1 again")
        (true (= 1 (mqtt:pending-request-id (mqtt:session-publish session "a" "b" :qos 1))))))))
