(defpackage #:luft.render.shaders
  (:use #:cl #:luv.shader)
  (:shadowing-import-from #:luv.shader #:step)
  (:documentation
   "Vertex and fragment stages that draw a surface chain of packed sites.")
  (:export #:+stocks-binding+
           #:+slots-binding+
           #:+orthographic-shadow-projector-binding+
           #:*deformations*
           #:deformation-index
           #:deform-point
           #:deform-normal
           #:stock-vertex-shader
           #:orthographic-stock-shadow-vertex-shader
           #:+stock-slots+
           #:+stock-lanes+
           #:+site-stock-shift+
           #:+site-stock-bits+
           #:+frame-binding+
           #:+sites-binding+
           #:+cells-binding+
           #:*frame-uniform-members*
           #:chamfer-fragment-shader
           #:temporal-chamfer-fragment-shader
           #:paper-fragment-shader
           #:temporal-paper-fragment-shader
           #:sky-fragment-shader
           #:temporal-sky-fragment-shader
           #:surface-vertex-shader
           #:field-vertex-shader
           #:field-fragment-shader
           #:temporal-field-fragment-shader
           #:ink-fragment-shader
           #:temporal-ink-fragment-shader
           #:stock-fragment-shader
           #:linear-stock-fragment-shader
           #:temporal-stock-fragment-shader
           #:clay-vertex-shader
           #:clay-fragment-shader
           #:temporal-clay-fragment-shader
           #:bevel-vertex-shader
           #:chamfer-vertex-shader
           #:sky-vertex-shader
           #:surface-vertices-per-face
           #:lens-fragment-shader
           #:present-fragment-shader
           #:temporal-resolve-fragment-shader
           #:+scene-binding+
           #:+sampler-binding+
           #:+lens-frame-binding+
           #:+current-binding+
           #:+motion-binding+
           #:+history-binding+
           #:+temporal-sampler-binding+
           #:+temporal-frame-binding+
           #:surface-fragment-shader
           #:temporal-surface-fragment-shader
           #:frame-uniform-block))

(defpackage #:luft.render
  (:use #:cl #:luv)
  (:local-nicknames (#:shaders #:luft.render.shaders)
                    (#:shader #:luv.shader)
                    (#:vec3 #:luv.arithmetic.lisp.vec3))
  (:documentation
   "A greenfield atelier renderer: a small block world as a boundary chain
of packed LUFT sites, drawn by vertex shaders pulling sites.")
  (:export #:world
           #:make-world
           #:world-domain
           #:world-solid
           #:world-slots
           #:world-stocks
           #:world-cell-p
           #:world-stock-slot
           #:world-vertical-p
           #:world-scene
           #:paint-cell
           #:*stock*
           #:with-stock
           #:fill-box
           #:scene
           #:make-scene
           #:scene-slots
           #:scene-stocks
           #:stock-table-data
           #:make-demo-scene
           #:scene-domain
           #:scene-solid
           #:scene-surface
           #:scene-sites
           #:scene-cell-bits
           #:scene-revision
           #:scene-cell-p
           #:apply-scene-edit
           #:refresh-scene
           #:fly-camera
           #:make-fly-camera
           #:camera-position
           #:camera-yaw
           #:camera-pitch
           #:camera-field-of-view
           #:camera-basis
           #:raycast-scene
           #:frame-uniform-data
           #:surface-technique
           #:make-surface-technique
           #:destroy-surface-technique
           #:surface-technique-construction-error
           #:surface-technique-construction-cause
           #:surface-technique-construction-retry-owner
           #:surface-technique-device
           #:surface-technique-layout
           #:surface-technique-pipeline
           #:surface-technique-pipeline-styles
           #:surface-technique-target-formats
           #:surface-technique-temporal-p
           #:surface-technique-output-space
           #:surface-technique-orthographic-shadow-depth-format
           #:surface-technique-orthographic-shadow-pipeline
           #:surface-frame-state
           #:make-surface-frame-state
           #:destroy-surface-frame-state
           #:surface-frame-state-technique
           #:surface-frame-state-bind-group
           #:surface-frame-state-orthographic-shadow-projector-buffer
           #:surface-frame-state-orthographic-shadow-bind-group
           #:surface-frame-state-uploaded-scene
           #:surface-frame-state-uploaded-scene-revision
           #:surface-frame-state-last-scene-upload-kind
           #:surface-frame-state-last-scene-upload-bytes
           #:surface-frame-state-last-scene-upload-writes
           #:synchronize-surface-frame-state
           #:write-surface-frame-state
           #:write-surface-shadow-projector
           #:draw-surface-frame
           #:draw-surface-shadow-frame
           #:renderer
           #:make-renderer
           #:renderer-device
           #:renderer-scene
           #:renderer-camera
           #:renderer-extent
           #:renderer-style
           #:renderer-pipeline-styles
           #:renderer-effects
           #:renderer-surface-technique
           #:renderer-surface-frame-state
           #:renderer-last-scene-upload-kind
           #:renderer-last-scene-upload-bytes
           #:renderer-last-scene-upload-writes
           #:*bevel-radius*
           #:*chamfer-width*
           #:*arris-softness*
           #:*field-vertical-radius*
           #:*clay-radius*
           #:*clay-melt*
           #:*clay-stocks*
           #:light
           #:light-name
           #:define-light
           #:find-light
           #:light-names
           #:*light*
           #:with-light
           #:*sun-direction*
           #:*sun-color*
           #:*sheen-strength*
           #:*fill-direction*
           #:*fill-strength*
           #:*ambient-light*
           #:*ground-color*
           #:*occlusion-strength*
           #:*wear-strength*
           #:*ink-width*
           #:*shadow-strength*
           #:material
           #:material-name
           #:define-material
           #:find-material
           #:material-names
           #:material-lanes
           #:material-spacing
           #:material-courses
           #:material-chamfer
           #:material-grit
           #:material-albedo
           #:*material*
           #:*deformation*
           #:*deform-strength*
           #:*deform-scale*
           #:*deform-centre*
           #:*erode-strength*
           #:*erode-grain*
           #:*chamfer-rule*
           #:*relief-convex*
           #:*relief-concave*
           #:*top-color*
           #:*side-color*
           #:*bottom-color*
           #:*exposure*
           #:*sky-color*
           #:*draw-sky*
           #:*focus-distance*
           #:*aperture*
           #:*fog-distance*
           #:destroy-renderer
           #:upload-scene
           #:encode-frame
           #:render-pixels
           #:render-to-png
           #:downsample-pixels
           #:capture-demo-png
           #:make-studio-scene
           #:atelier-scene
           #:atelier-cameras
           #:atelier-pieces
           #:render-piece-sheet
           #:render-view
           #:render-light-sheet
           #:fill-disc
           #:fill-ring
           #:carve-arch
           #:ring-arch
           #:corbel
           #:crenellate
           #:crenellate-disc
           #:fill-stairs
           #:spiral-stair
           #:ground-height
           #:lay-ground
           #:grass-the-flats
           #:column-top
           #:scatter-boulders
           #:plant-tree
           #:plant-wood
           #:arch-rise
           #:studio-cameras
           #:studio-camera
           #:render-contact-sheet
           #:film-studio-orbit
           #:film-atelier-flight
           #:film-atelier-construction
           #:film-clay-breath
           #:viewer
           #:main
           #:start-viewer
           #:stop-viewer
           #:viewer-renderer
           #:*viewer*))
