(defpackage #:luv.slug
  (:use #:cl)
  (:local-nicknames (#:spv #:luv.spir-v)
                    (#:arith-lisp #:luv.arithmetic.lisp))
  (:export #:slug-outline-error
           #:slug-outline-error-reason
           #:slug-outline-error-details
           #:slug-point
           #:make-slug-point
           #:slug-point-x
           #:slug-point-y
           #:slug-quadratic
           #:make-slug-quadratic
           #:slug-quadratic-start
           #:slug-quadratic-control
           #:slug-quadratic-end
           #:make-slug-line
           #:slug-outline
           #:make-slug-outline
           #:slug-outline-contours
           #:slug-outline-curves
           #:slug-contour-signed-area
           #:slug-contour-orientation
           #:slug-band
           #:slug-band-curve-indices
           #:slug-band-ascending-curve-indices
           #:slug-packed-outline
           #:slug-packed-outline-curves
           #:slug-packed-outline-min-x
           #:slug-packed-outline-min-y
           #:slug-packed-outline-max-x
           #:slug-packed-outline-max-y
           #:slug-packed-outline-horizontal-bands
           #:slug-packed-outline-vertical-bands
           #:pack-slug-outline
           #:slug-serialized-outline
           #:slug-serialized-outline-packed-outline
           #:slug-serialized-outline-curve-width
           #:slug-serialized-outline-band-width
           #:slug-serialized-outline-curve-half-words
           #:slug-serialized-outline-curve-texel-count
           #:slug-serialized-outline-curve-upload-data
           #:slug-serialized-outline-curve-texture-size
           #:slug-serialized-outline-band-uint16-words
           #:slug-serialized-outline-band-texel-count
           #:slug-serialized-outline-band-upload-data
           #:slug-serialized-outline-band-texture-size
           #:slug-serialized-outline-horizontal-band-count
           #:slug-serialized-outline-vertical-band-count
           #:serialize-slug-outline
           #:slug-shaping-error
           #:slug-shaping-error-reason
           #:slug-shaping-error-details
           #:slug-shaped-glyph
           #:slug-shaped-glyph-glyph-id
           #:slug-shaped-glyph-cluster
           #:slug-shaped-glyph-x-advance
           #:slug-shaped-glyph-y-advance
           #:slug-shaped-glyph-x-offset
           #:slug-shaped-glyph-y-offset
           #:slug-shaped-text
           #:slug-shaped-text-glyphs
           #:slug-shaped-text-units-per-em
           #:slug-shaped-text-x-advance
           #:slug-shaped-text-y-advance
           #:shape-slug-text
           #:slug-glyph
           #:make-slug-glyph
           #:slug-glyph-character
           #:slug-glyph-outline
           #:slug-glyph-advance-width
           #:slug-glyph-left-side-bearing
           #:slug-glyph-units-per-em
           #:slug-outline-from-zpb-glyph
           #:make-slug-glyph-from-zpb-glyph
           #:load-slug-glyph-index
           #:load-slug-glyph
           #:map-slug-outline-points
           #:normalize-slug-glyph-outline
           #:slug-device-glyph
           #:slug-device-glyph-key
           #:slug-device-glyph-glyph-id
           #:slug-device-glyph-serialized
           #:slug-glyph-placement
           #:make-slug-glyph-placement
           #:slug-glyph-placement-glyph-id
           #:slug-glyph-placement-resource
           #:slug-glyph-placement-origin-x
           #:slug-glyph-placement-origin-y
           #:slug-glyph-placement-outline-min-x
           #:slug-glyph-placement-outline-min-y
           #:slug-glyph-placement-outline-max-x
           #:slug-glyph-placement-outline-max-y
           #:slug-glyph-atlas
           #:make-slug-glyph-atlas
           #:slug-glyph-atlas-locations
           #:slug-glyph-atlas-band-texel-count
           #:slug-glyph-atlas-curve-texel-count
           #:slug-glyph-atlas-band-view
           #:slug-glyph-atlas-curve-view
           #:slug-glyph-cache
           #:make-slug-glyph-cache
           #:cached-slug-shaped-text
           #:make-slug-glyph-placements
           #:slug-text-extents
           #:slug-glyph-atlas-for
           #:slug-glyph-cache-resource-count
           #:release-slug-glyph-cache
           #:slug-atlas-fragment-specification
           #:slug-root-eligibility
           #:slug-quadratic-outline
           #:slug-bezier-vertex-specification
           #:slug-bezier-fragment-specification
           #:slug-banded-fragment-specification
           ;; The tunable values, and their names in shader source.
           #:*slug-filter-width*
           #:*slug-fill-rule*
           #:*slug-optical-weight*
           #:*slug-footprint-norm*
           #:*slug-early-exit*
           #:*slug-root-epsilon*
           #:*slug-debug-view*
           #:*slug-dilation-pixels*
           #:*slug-static-padding*
           #:*slug-maximum-band-count*
           #:*slug-band-epsilon*
           #:*slug-share-band-lists*
           #:slug-filter-width
           #:slug-fill-rule
           #:slug-optical-weight
           #:slug-footprint-norm
           #:slug-early-exit
           #:slug-root-epsilon
           #:slug-debug-view
           #:slug-dilation-pixels
           #:slug-dilation-em
           #:slug-font-cap-height
           #:slug-cap-height-aligned-size
           #:choose-slug-band-count))
